# Generated by Django 3.2 on 2022-09-12 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи категории'),
        ),
    ]
